defaults: ../../grpo_math_1B_trtllm.yaml
grpo:
  num_prompts_per_step: 8
  num_generations_per_prompt: 4
  max_val_samples: 64
  val_batch_size: 64
checkpointing:
  checkpoint_dir: results/grpo-qwen2.5-0.5b-1n4g-megatron-trtllm
policy:
  model_name: Qwen/Qwen2.5-0.5B
  tokenizer:
    name: Qwen/Qwen2.5-0.5B
  train_global_batch_size: 32
  train_micro_batch_size: 1
  logprob_batch_size: 4
  max_total_sequence_length: 1024
  make_sequence_length_divisible_by: 1
  optimizer: null
  scheduler: null
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
  generation:
    max_new_tokens: 512
logger:
  log_dir: logs/grpo-qwen2.5-0.5b-1n4g-megatron-trtllm
  wandb:
    project: nemo-rl
    name: grpo-qwen2.5-0.5b-1n4g-megatron-trtllm
cluster:
  gpus_per_node: 4
